---
title             : "Factorial structure of the indicators in Big Five Plus Inventory"
shorttitle        : "Factorial structure of the indicators in Big Five Plus Inventory"
author: 
  - name          : "Cristian Opariuc-Dan"
    affiliation   : "1,2,3"
    corresponding : yes    # Define only one corresponding author
    address       : "Ovidius University Campus, Aleea Universității, No. 2, Constanța, Romania"
    email         : "copariuc@gmail.com"
    role:         # Contributorship roles (e.g., CRediT, https://casrai.org/credit/)
      - Conceptualization
      - Writing - Original Draft Preparation
      - Writing - Data analysis
  - name          : "Gabriela Nicuță"
    affiliation   : "3"
    role:
      - Writing - Systematic review
      - Writing - Data analysis
      - Proofreading
  - name          : "Ticu Constantin"
    affiliation   : "3"
    role:
      - Data provider
      - Writing - Review & Editing
affiliation:
  - id            : "1"
    institution   : "Ovidius University, Constanta, Romania"
  - id            : "2"
    institution   : "Bucharest University, Bucharest, Romania"
  - id            : "3"
    institution   : "Al. I. Cuza University, Iassy, Romania"
authornote: |
  
  The authors thanks Prof. Dr. Constantin Ticu and the PsihoProfile team for making available over 14000 data used in this analysis.
  
  The data in this paper comes form the Romanian version of BigFive Plus inventory[@BigFive-plus], being collected online through the [PsihoProfile site](http://www.psihoprofile.ro/)
abstract: |
  TO BE DONE AT THE END
keywords          : "BigFive, Confirmatory Factor Analysis, Reliability analysis"
wordcount         : "502 words in text body, 49 words in reference section"
bibliography      : ["r-references.bib", "Big Five Plus.bib"]
link-citations    : TRUE
biblio-style      : "apalike"
floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : yes
mask              : no
draft             : yes
documentclass     : "apa7"
csl               : "`r system.file('rmd', 'apa7.csl', package = 'papaja')`"
classoption       : "man"
output            : papaja::apa6_pdf
editor_options: 
  chunk_output_type: console
header-includes:
  - |
    \makeatletter
    \renewcommand{\paragraph}{\@startsection{paragraph}{4}{\parindent}%
      {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
      {-1em}%
      {\normalfont\normalsize\bfseries\typesectitle}}
    
    \renewcommand{\subparagraph}[1]{\@startsection{subparagraph}{5}{1em}%
      {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
      {-\z@\relax}%
      {\normalfont\normalsize\bfseries\itshape\hspace{\parindent}{#1}\textit{\addperi}}{\relax}}
    \makeatother
  - \usepackage[document]{ragged2e}
---

```{r setup, include = FALSE}
  # Including necessary libraries
  library(papaja); library(knitr)
  # Including references file for R libraries
  r_refs("r-references.bib")
```

```{r analysis-preferences}
  # Seed for random number generation
  set.seed(4482)
  knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```



## Scales' reliability
```{r reliability, echo=FALSE, include=FALSE}
  source("03 - Consistente.R")
```

```{r authorCronbach, echo=FALSE}
  # Building Table
  rm(cron.tab.auth)
  # cron.tab.auth <- data.frame('EXTRAVERSION', .920, .914, .917)
  # colnames(cron.tab.auth) <- c("Dimension/Facet", "Male", "Female", "Normative sample")
  # cron.tab.auth <- rbind(cron.tab.auth, c('- Friendliness', .742, .748, .744))
  # cron.tab.auth <- rbind(cron.tab.auth, c('- Gregariousness', .781, .767, .775))
  # cron.tab.auth <- rbind(cron.tab.auth, c('- Assertiveness', .712, .692, .702))
  # cron.tab.auth <- rbind(cron.tab.auth, c('- Activity level', .727, .669, .696))
  # cron.tab.auth <- rbind(cron.tab.auth, c('- Excitement seeking', .802, .762, .786))
  # cron.tab.auth <- rbind(cron.tab.auth, c('- Cheerfulness', .716, .750, .735))
  
  cron.tab.auth <- data.frame('AGREEABLENESS', .844, .826, .838)
  cron.tab.auth <- rbind(cron.tab.auth, c('- Trust', .647, .672, .660))
  cron.tab.auth <- rbind(cron.tab.auth, c('- Morality', .711, .703, .708))
  cron.tab.auth <- rbind(cron.tab.auth, c('- Altruism', .655, .650, .653))
  cron.tab.auth <- rbind(cron.tab.auth, c('- Cooperation', .645, .635, .641))
  cron.tab.auth <- rbind(cron.tab.auth, c('- Modesty', .650, .666, .660))
  cron.tab.auth <- rbind(cron.tab.auth, c('- Sympathy', .717, .653, .705))

  # cron.tab.auth <- rbind(cron.tab.auth, c('NEUROTICISM', .875, .877, .879))
  # cron.tab.auth <- rbind(cron.tab.auth, c('- Anxiety', .700, .700, .708))
  # cron.tab.auth <- rbind(cron.tab.auth, c('- Anger', .834, .839, .839))
  # cron.tab.auth <- rbind(cron.tab.auth, c('- Depression', .737, .717, .730))
  # cron.tab.auth <- rbind(cron.tab.auth, c('- Timidity', .623, .665, .649))
  # cron.tab.auth <- rbind(cron.tab.auth, c('- Immoderation', .779, .738, .761))
  # cron.tab.auth <- rbind(cron.tab.auth, c('- Vulnerability', .741, .742, .746))
  # 
  # cron.tab.auth <- rbind(cron.tab.auth, c('CONSCIENTIOUSNESS', .857, .820, .840))
  # cron.tab.auth <- rbind(cron.tab.auth, c('- Self-efficacy', .670, .675, .679))
  # cron.tab.auth <- rbind(cron.tab.auth, c('- Orderliness', .653, .647, .650))
  # cron.tab.auth <- rbind(cron.tab.auth, c('- Dutifulness', .674, .608, .648))
  # cron.tab.auth <- rbind(cron.tab.auth, c('- Achievement-striving', .655, .639, .646))
  # cron.tab.auth <- rbind(cron.tab.auth, c('- Self-discipline', .699, .596, .655))
  # cron.tab.auth <- rbind(cron.tab.auth, c('- Cautiousness', .748, .704, .729))
  # 
  # cron.tab.auth <- rbind(cron.tab.auth, c('OPENNESS TO EXPERIENCE', .820, .809, .813))
  # cron.tab.auth <- rbind(cron.tab.auth, c('- Imagination', .653, .665, .658))
  # cron.tab.auth <- rbind(cron.tab.auth, c('- Artistic interests', .744, .702, .732))
  # cron.tab.auth <- rbind(cron.tab.auth, c('- Emotionality', .421, .510, .671))
  # cron.tab.auth <- rbind(cron.tab.auth, c('- Adventurousness', .753, .744, .750))
  # cron.tab.auth <- rbind(cron.tab.auth, c('- Intellect', .564, .579, .572))
  # cron.tab.auth <- rbind(cron.tab.auth, c('- Liberalism', .628, .587, .607))
  
  cron.tab.auth
```

### Agreeableness
```{r agreeableness, echo=FALSE}
  # Generating table
  con.df <- as.data.frame(AGREEABL$total)
  con.df <- rbind(con.df, AGR.Trust$total, AGR.Moral$total, AGR.Altru$total, 
                  AGR.Coope$total, AGR.Modes$total, AGR.Sympa$total)
  con.df <- select(con.df, c(-5, -9))
  con.df <- cbind(con.df, as.numeric(cron.tab.auth[1:7, 4]))  # Authors' Alpha
  con.df <- round(con.df, 2)
  # Adding Confidence Intervals
  ci <- c(paste(round(CI.AGREEABL$lower.ci, 3), "-", round(CI.AGREEABL$upper.ci, 3)),
          paste(round(CI.AGR.Trust$lower.ci, 3), "-", round(CI.AGR.Trust$upper.ci, 3)),
          paste(round(CI.AGR.Moral$lower.ci, 3), "-", round(CI.AGR.Moral$upper.ci, 3)),
          paste(round(CI.AGR.Altru$lower.ci, 3), "-", round(CI.AGR.Altru$upper.ci, 3)),
          paste(round(CI.AGR.Coope$lower.ci, 3), "-", round(CI.AGR.Coope$upper.ci, 3)),
          paste(round(CI.AGR.Modes$lower.ci, 3), "-", round(CI.AGR.Modes$upper.ci, 3)),
          paste(round(CI.AGR.Sympa$lower.ci, 3), "-", round(CI.AGR.Sympa$upper.ci, 3))
          )
  con.df <- cbind(con.df[, 1], ci, con.df[, 2:8])
  # Setting up variables' name
  Var.names <- c( "AGREEABLENESS", 
                  "Trust", "Morality", "Altruism",
                  "Cooperation", "Modesty", "Sympathy")
  con.df <- cbind(Var.names, con.df)    # Name of the variables
  # Changing the names of the columns
  names(con.df) <- c("Variable", "Alpha", "CI 95%", "Std", "G6", "Avg r", "Avg SE", 
                     "Mean", "SD", "Initial")
  
  kable(con.df, format = "latex", digits = 3, booktabs = T, row.names = F,
        caption = "Agreeableness - Global alpha Cronbach",
        align = c("l", "r", "r", "r", "r", "r", "r", "r", "r", "r"))
```
```{r agreeableness-boot, echo=FALSE}

  # Adding value after resampling
  alpha.boot <- c(paste(round(min(AGREEABL$boot[, 1]), 3), "-", round(max(AGREEABL$boot[, 1]), 3)),
                  paste(round(min(AGR.Trust$boot[, 1]), 3), "-", round(max(AGR.Trust$boot[, 1]), 3)),
                  paste(round(min(AGR.Moral$boot[, 1]), 3), "-", round(max(AGR.Moral$boot[, 1]), 3)),
                  paste(round(min(AGR.Altru$boot[, 1]), 3), "-", round(max(AGR.Altru$boot[, 1]), 3)),
                  paste(round(min(AGR.Coope$boot[, 1]), 3), "-", round(max(AGR.Coope$boot[, 1]), 3)),
                  paste(round(min(AGR.Modes$boot[, 1]), 3), "-", round(max(AGR.Modes$boot[, 1]), 3)),
                  paste(round(min(AGR.Sympa$boot[, 1]), 3), "-", round(max(AGR.Sympa$boot[, 1]), 3))
                  )
  unidim.boot <- c(paste(round(min(AGREEABL$boot[, 7]), 3), "-", round(max(AGREEABL$boot[, 7]), 3)),
                   paste(round(min(AGR.Trust$boot[, 7]), 3), "-", round(max(AGR.Trust$boot[, 7]), 3)),
                   paste(round(min(AGR.Moral$boot[, 7]), 3), "-", round(max(AGR.Moral$boot[, 7]), 3)),
                   paste(round(min(AGR.Altru$boot[, 7]), 3), "-", round(max(AGR.Altru$boot[, 7]), 3)),
                   paste(round(min(AGR.Coope$boot[, 7]), 3), "-", round(max(AGR.Coope$boot[, 7]), 3)),
                   paste(round(min(AGR.Modes$boot[, 7]), 3), "-", round(max(AGR.Modes$boot[, 7]), 3)),
                   paste(round(min(AGR.Sympa$boot[, 7]), 3), "-", round(max(AGR.Sympa$boot[, 7]), 3))
                   )
  gfi.boot <- c(paste(round(min(AGREEABL$boot[, 8]), 3), "-", round(max(AGREEABL$boot[, 8]), 3)),
                paste(round(min(AGR.Trust$boot[, 8]), 3), "-", round(max(AGR.Trust$boot[, 8]), 3)),
                paste(round(min(AGR.Moral$boot[, 8]), 3), "-", round(max(AGR.Moral$boot[, 8]), 3)),
                paste(round(min(AGR.Altru$boot[, 8]), 3), "-", round(max(AGR.Altru$boot[, 8]), 3)),
                paste(round(min(AGR.Coope$boot[, 8]), 3), "-", round(max(AGR.Coope$boot[, 8]), 3)),
                paste(round(min(AGR.Modes$boot[, 8]), 3), "-", round(max(AGR.Modes$boot[, 8]), 3)),
                paste(round(min(AGR.Sympa$boot[, 8]), 3), "-", round(max(AGR.Sympa$boot[, 8]), 3))
                )
  con.boot <- cbind.data.frame(con.df[, 2], alpha.boot, unidim.boot, gfi.boot)
  con.boot <- cbind(Var.names, con.boot)    # Name of the variables
   # Changing the names of the columns
  names(con.boot) <- c("Variable", "Base alpha", "Alpha boot", "Unidim", "GFI")
  
  kable(con.boot, format = "latex", digits = 3, booktabs = T, row.names = F,
        caption = "Agreeableness - Global alpha Cronbach after bootstrapping",
        align = c("l", "r", "r", "r"))
```
```{r agreeableness-items, echo=FALSE}
  # Generating table
  con.items <- rbind.data.frame(round(AGR.Trust$alpha.drop, 3),
                                round(AGR.Moral$alpha.drop, 3),
                                round(AGR.Altru$alpha.drop, 3),
                                round(AGR.Coope$alpha.drop, 3),
                                round(AGR.Modes$alpha.drop, 3),
                                round(AGR.Sympa$alpha.drop, 3)
                                )
  con.items <- select(con.items, c(-5, -7, -8))
  fac.alpha <- c(rep(round(AGR.Trust$total[1, 1], 3), 8),
                 rep(round(AGR.Moral$total[1, 1], 3), 8),
                 rep(round(AGR.Altru$total[1, 1], 3), 8),
                 rep(round(AGR.Coope$total[1, 1], 3), 8),
                 rep(round(AGR.Modes$total[1, 1], 3), 8),
                 rep(round(AGR.Sympa$total[1, 1], 3), 8)
                 )
  fac.names <-c(rep("Trust", 8),
                rep("Morality", 8),
                rep("Altruism", 8),
                rep("Cooperation", 8),
                rep("Modesty", 8),
                rep("Sympathy", 8)
                )
  con.items <- cbind(fac.names, fac.alpha, con.items)
   # Changing the names of the columns
  names(con.items) <- c("Facet name", "Facet" ,"Deleted", "Std", "G6", "Avg r", "SE")
  
  kable(con.items[1:24,], format = "latex", digits = 3, booktabs = T, row.names = T, align = "r",
        caption = "Alpha if item is deleted (Trust, Morality, Altruism)",label = "AGR-items-1")
  kable(con.items[25:48,], format = "latex", digits = 3, booktabs = T, row.names = T, align = "r",
        caption = "Alpha Cronbach if item is deleted (Cooperation, Modesty,
        Sympathy)", label = "AGR-items-2")
```

The results obtained for the **Agreeableness dimension** 

## Stop

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}




<div id="refs" custom-style="Bibliography"></div>
\endgroup
